version: '3'
services:
  redis:
    image: redis
    container_name: app_redis
    ports:
      - "6379:6379"
  database:
    image: postgres
    container_name: app_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
volumes:
  db_data: